In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
inputs = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)

In [4]:
inputs = df.drop('Survived', axis = 1)
target = df['Survived']

In [5]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [ ]:
# fillna() is targeted replacement:

df['Age'] = df['Age'].fillna(df['Age'].median())

In [7]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [11]:
df = pd.get_dummies(df, columns = ['Embarked'])

KeyError: "None of [Index(['Embarked'], dtype='object')] are in the [columns]"

In [10]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [14]:
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [13]:
df = df.drop(['Cabin'], axis = 1)

In [16]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,False,True

In [17]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le_name = LabelEncoder()
le_ticket = LabelEncoder()

In [21]:
inputs['name_n'] = le_name.fit_transform(inputs['Name'])
inputs['ticket_n'] = le_name.fit_transform(inputs['Ticket'])
inputs.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,name_n,ticket_n
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,108,523
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,190,596
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,353,669
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,272,49
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,15,472

In [25]:
inputs_n = inputs.drop(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
'Fare', 'Cabin', 'Embarked'], axis = 'columns')

inputs_n

     name_n  ticket_n
0       108       523
1       190       596
2       353       669
3       272        49
4        15       472
..      ...       ...
886     548       101
887     303        14
888     413       675
889      81         8
890     220       466

[891 rows x 2 columns]

In [26]:
from sklearn import tree

In [27]:
model = tree.DecisionTreeClassifier()

In [ ]:
model.fit(inputs_n, )

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,False,True

In [30]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Embarked_C',
         'Embarked_Q', 'Embarked_S'], axis = 'columns', inplace = True)

In [31]:
df.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    0  22.0   7.2500
1         1       1    1  38.0  71.2833
2         1       3    1  26.0   7.9250
3         1       1    1  35.0  53.1000
4         0       3    0  35.0   8.0500

In [32]:
inputs = df.drop('Survived', axis = 'columns')
target = df.Survived

In [33]:
inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [34]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5    28.0
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [35]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [36]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3  NaN  22.0   7.2500
1       1  NaN  38.0  71.2833
2       3  NaN  26.0   7.9250
3       1  NaN  35.0  53.1000
4       3  NaN  35.0   8.0500

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.4)

In [39]:
len(X_train)

534

In [40]:
len(X_test)

357

In [41]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [42]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [43]:
model.score(X_test, y_test)

0.6330532212885154